### ISSUE TITLE
ERR : components/connectivity/agent_tiny/examples/agent_tiny_test1.c->lwm2m_main()->if(ATINY_OK != atiny_init(atiny_params, &g_phandle))

### ISSUE THREAD

**Issue by luminais** [LiteOSv2/IoT2.0#5]
https://github.com/LiteOSv2/IoT2.0/blob/a2b2b8008ac70e5f5984eeeb2ac0f9cf18af424c/Huawei_LiteOS/components/connectivity/agent_tiny/examples/agent_tiny_test1.c#L142

https://github.com/LiteOSv2/IoT2.0/blob/522406e5ec5fad7654615f1082e8c2d1251ceaf8/Huawei_LiteOS/components/connectivity/agent_tiny/examples/agent_tiny_test1.c#L193

atiny_params所指对象为全局静态变量，LOS_MemFree()会出错

**Comment by IOTBaicheng** [comment]
atiny_params不应该调用LOS_MemFree进行释放。

**Comment by IOTBaicheng** [comment]
solved at: af54ab2e01a1504999e3f288bdbd2101f960ff65
